---
name: Locale-Maketext-Extract-Plugin-XSL
version: 0.3
author:
  - 'Michael Kroell <pepl@cpan.org>'
abstract: XSL file parser
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Locale::Maketext::Lexicon: 0.7
  Regexp::Common: 0
  XML::LibXML: 1.61
build_requires:
  Test::More: 0
provides:
  Locale::Maketext::Extract::Plugin::XSL:
    file: lib/Locale/Maketext/Extract/Plugin/XSL.pm
    version: 0.3
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
